name: Docker Image CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  HEALTH_CHECK: goat/k8s-goat-healthcheck
  SYSTEM_MONITOR: goat/k8s-goat-system-monitor
  HIDDEN_LAYERS: goat/k8s-goat-hidden-in-layers 
  HUNGER_CHECK: goat/k8s-goat-hunger-check
  POOR-REGISTRY: goat/k8s-goat-poor-registry
  INTERNAL_API: goat/k8s-goat-internal-api
  INFO_APP: goat/k8s-goat-info-app
  BATCH_CHECK: goat/k8s-goat-batch-check
  GOAT_HOME: goat/k8s-goat-home
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

 #   - name: Build the Docker image
 #     run: docker build infrastructure/health-check/ --file infrastructure/health-check/Dockerfile --tag ${{ secrets.ACR_ENDPOINT }}/${{ env.HEALTH_CHECK }}:${{ env.GITHUB_RUN_ID }}
 #   - name: Docker meta
 #     id: meta
 #     uses: docker/metadata-action@v3
 #     with:
 #       # list of Docker images to use as base name for tags
 #       images: |
 #         ${{ secrets.ACR_ENDPOINT }}/${{ env.HEALTH_CHECK }}
 #       
        # generate Docker tags based on the following events/attributes
 #       tags: |
 #         type=schedule
 #         type=ref,event=branch
 #         type=ref,event=pr
 #         type=semver,pattern={{version}}
  #        type=semver,pattern={{major}}.{{minor}}
  #        type=semver,pattern={{major}}
  #        type=sha
 #   -
 #     name: Set up QEMU
 #     uses: docker/setup-qemu-action@v1
 #   -
 #     name: Set up Docker Buildx
 #     uses: docker/setup-buildx-action@v1          
 #   - name: Log into registry
 #     uses: docker/login-action@v1
 #     with:
 #       registry: ${{ secrets.ACR_ENDPOINT }}
 #       username: ${{ secrets.ACR_USERNAME }}
 #       password: ${{ secrets.ACR_PASSWORD }}  

    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        registry: ${{ secrets.ACR_ENDPOINT }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}  
    - name: Build the Docker image HEALTHCHECK
      run: |
        echo "github.sha=$GITHUB_SHA"
        docker build infrastructure/health-check/ --file infrastructure/health-check/Dockerfile --tag ${{ secrets.ACR_ENDPOINT }}/${{ env.HEALTH_CHECK }}:${{ github.sha }}
    - name: Build the Docker image SYSTEM_MONITOR
      run: |
        echo "github.sha=$GITHUB_SHA"
        docker build infrastructure/system-monitor/ --file infrastructure/system-monitor/Dockerfile --tag ${{ secrets.ACR_ENDPOINT }}/${{ env.SYSTEM_MONITOR }}:${{ github.sha }}
    - name: Build the Docker image HIDDEN_LAYERS
      run: |
        echo "github.sha=$GITHUB_SHA"
        docker build infrastructure/hidden-in-layers/ --file infrastructure/hidden-in-layers/Dockerfile --tag ${{ secrets.ACR_ENDPOINT }}/${{ env.HIDDEN_LAYERS }}:${{ github.sha }}
    - name: Build the Docker image HUNGER_CHECK
      run: |
        echo "github.sha=$GITHUB_SHA"
        docker build infrastructure/hunger-check/ --file infrastructure/hunger-check/Dockerfile --tag ${{ secrets.ACR_ENDPOINT }}/${{ env.HUNGER_CHECK }}:${{ github.sha }}
    - name: Build the Docker image POOR_REGISTRY
      run: |
        echo "github.sha=$GITHUB_SHA"
        docker build infrastructure/poor-registry/ --file infrastructure/poor-registry/Dockerfile --tag ${{ secrets.ACR_ENDPOINT }}/${{ env.POOR_REGISTRY }}:${{ github.sha }}
    - name: Build the Docker image INTERNAL_API
      run: |
        echo "github.sha=$GITHUB_SHA"
        docker build infrastructure/internal-api/ --file infrastructure/internal-api/Dockerfile --tag ${{ secrets.ACR_ENDPOINT }}/${{ env.INTERNAL_API }}:${{ github.sha }}
    - name: Build the Docker image INFO_APP
      run: |
        echo "github.sha=$GITHUB_SHA"
        docker build infrastructure/info-app/ --file infrastructure/info-app/Dockerfile --tag ${{ secrets.ACR_ENDPOINT }}/${{ env.INFO_APP }}:${{ github.sha }}       
        
    - name: Build the Docker image BATCH_CHECK
      run: |
        echo "github.sha=$GITHUB_SHA"
        docker build infrastructure/batch-check/ --file infrastructure/batch-check/Dockerfile --tag ${{ secrets.ACR_ENDPOINT }}/${{ env.BATCH_CHECK }}:${{ github.sha }} 
    - name: Build the Docker image GOAT_HOME
      run: |
        echo "github.sha=$GITHUB_SHA"
        docker build infrastructure/goat-home/ --file infrastructure/goat-home/Dockerfile --tag ${{ secrets.ACR_ENDPOINT }}/${{ env.GOAT_HOME }}:${{ github.sha }}    
    - name: Build the Docker image GOAT_HOME
      run: |
        echo "github.sha=$GITHUB_SHA"
        docker build infrastructure/goat-home/ --file infrastructure/goat-home/Dockerfile --tag ${{ secrets.ACR_ENDPOINT }}/${{ env.GOAT_HOME }}:${{ github.sha }}    
    - name: Push Docker image 
      run: |
        docker push  ${{ secrets.ACR_ENDPOINT }}/${{ env.HEALTH_CHECK }}:${{ github.sha }}
        docker push  ${{ secrets.ACR_ENDPOINT }}/${{ env.SYSTEM_MONITOR }}:${{ github.sha }}
        docker push  ${{ secrets.ACR_ENDPOINT }}/${{ env.HIDDEN_LAYERS }}:${{ github.sha }}
        docker push  ${{ secrets.ACR_ENDPOINT }}/${{ env.HUNGER_CHECK }}:${{ github.sha }}
        docker push  ${{ secrets.ACR_ENDPOINT }}/${{ env.POOR_REGISTRY }}:${{ github.sha }}
        docker push  ${{ secrets.ACR_ENDPOINT }}/${{ env.INTERNAL_API }}:${{ github.sha }}
        docker push  ${{ secrets.ACR_ENDPOINT }}/${{ env.GOAT_HOME }}:${{ github.sha }}
        docker push  ${{ secrets.ACR_ENDPOINT }}/${{ env.BATCH_CHECK }}:${{ github.sha }}
        
    - uses: Azure/container-scan@v0
      name: 'Docker - Azure Defender Scan'
      continue-on-error: true
      id: container-scan1
      with:
        image-name: ${{ secrets.ACR_ENDPOINT }}/${{ env.HEALTH_CHECK }}:${{ github.sha }}
        severity-threshold: WARN

    - name: Post logs to appinsights
      uses: Azure/publish-security-assessments@v0
      with: 
        scan-results-path: ${{ steps.container-scan1.outputs.scan-report-path }}
        connection-string: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}
        subscription-token: ${{ secrets.AZ_SUBSCRIPTION_TOKEN }}

    - uses: Azure/container-scan@v0
      name: 'Docker - Azure Defender Scan'
      continue-on-error: true
      id: container-scan2
      with:
        image-name: ${{ secrets.ACR_ENDPOINT }}/${{ env.SYSTEM_MONITOR }}:${{ github.sha }}
        severity-threshold: WARN

    - name: Post logs to appinsights
      uses: Azure/publish-security-assessments@v0
      with: 
        scan-results-path: ${{ steps.container-scan2.outputs.scan-report-path }}
        connection-string: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}
        subscription-token: ${{ secrets.AZ_SUBSCRIPTION_TOKEN }}
  
  
  
    - uses: Azure/container-scan@v0
      name: 'Docker - Azure Defender Scan'
      continue-on-error: true
      id: container-scan3
      with:
        image-name: ${{ secrets.ACR_ENDPOINT }}/${{ env.HIDDEN_LAYERS }}:${{ github.sha }}
        severity-threshold: WARN

    - name: Post logs to appinsights
      uses: Azure/publish-security-assessments@v0
      with: 
        scan-results-path: ${{ steps.container-scan3.outputs.scan-report-path }}
        connection-string: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}
        subscription-token: ${{ secrets.AZ_SUBSCRIPTION_TOKEN }}
        

    - uses: Azure/container-scan@v0
      name: 'Docker - Azure Defender Scan'
      continue-on-error: true
      id: container-scan4
      with:
        image-name: ${{ secrets.ACR_ENDPOINT }}/${{ env.HUNGER_CHECK }}:${{ github.sha }}
        severity-threshold: WARN

    - name: Post logs to appinsights
      uses: Azure/publish-security-assessments@v0
      with: 
        scan-results-path: ${{ steps.container-scan4.outputs.scan-report-path }}
        connection-string: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}
        subscription-token: ${{ secrets.AZ_SUBSCRIPTION_TOKEN }}




    - uses: Azure/container-scan@v0
      name: 'Docker - Azure Defender Scan'
      continue-on-error: true
      id: container-scan5
      with:
        image-name: ${{ secrets.ACR_ENDPOINT }}/${{ env. POOR-REGISTRY }}:${{ github.sha }}
        severity-threshold: WARN

    - name: Post logs to appinsights
      uses: Azure/publish-security-assessments@v0
      with: 
        scan-results-path: ${{ steps.container-scan5.outputs.scan-report-path }}
        connection-string: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}
        subscription-token: ${{ secrets.AZ_SUBSCRIPTION_TOKEN }}
        
        
    - uses: Azure/container-scan@v0
      name: 'Docker - Azure Defender Scan'
      continue-on-error: true
      id: container-scan6
      with:
        image-name: ${{ secrets.ACR_ENDPOINT }}/${{ env.INTERNAL_API }}:${{ github.sha }}
        severity-threshold: WARN

    - name: Post logs to appinsights
      uses: Azure/publish-security-assessments@v0
      with: 
        scan-results-path: ${{ steps.container-scan6.outputs.scan-report-path }}
        connection-string: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}
        subscription-token: ${{ secrets.AZ_SUBSCRIPTION_TOKEN }}
        
        
        
    - uses: Azure/container-scan@v0
      name: 'Docker - Azure Defender Scan'
      continue-on-error: true
      id: container-scan7
      with:
        image-name: ${{ secrets.ACR_ENDPOINT }}/${{ env.INFO_APP }}:${{ github.sha }}
        severity-threshold: WARN

    - name: Post logs to appinsights
      uses: Azure/publish-security-assessments@v0
      with: 
        scan-results-path: ${{ steps.container-scan7.outputs.scan-report-path }}
        connection-string: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}
        subscription-token: ${{ secrets.AZ_SUBSCRIPTION_TOKEN }}        



    - uses: Azure/container-scan@v0
      name: 'Docker - Azure Defender Scan'
      continue-on-error: true
      id: container-scan8
      with:
        image-name: ${{ secrets.ACR_ENDPOINT }}/${{ env.BATCH_CHECK }}:${{ github.sha }}
        severity-threshold: WARN

    - name: Post logs to appinsights
      uses: Azure/publish-security-assessments@v0
      with: 
        scan-results-path: ${{ steps.container-scan8.outputs.scan-report-path }}
        connection-string: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}
        subscription-token: ${{ secrets.AZ_SUBSCRIPTION_TOKEN }} 

    - uses: Azure/container-scan@v0
      name: 'Docker - Azure Defender Scan'
      continue-on-error: true
      id: container-scan9
      with:
        image-name: ${{ secrets.ACR_ENDPOINT }}/${{ env.GOAT_HOME }}:${{ github.sha }}
        severity-threshold: WARN

    - name: Post logs to appinsights
      uses: Azure/publish-security-assessments@v0
      with: 
        scan-results-path: ${{ steps.container-scan9.outputs.scan-report-path }}
        connection-string: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}
        subscription-token: ${{ secrets.AZ_SUBSCRIPTION_TOKEN }} 
