name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  HEALTH_CHECK: goat/k8s-goat-health-check
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
    - name: Build the Docker image
      run: docker build infrastructure/health-check/ --file infrastructure/health-check/Dockerfile --tag ${{ secrets.ACR_ENDPOINT }}/${{ env.HEALTH_CHECK }}:${{ steps.tag.outputs.tag }}
    - name: Log into registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ACR_ENDPOINT }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}  
    - name: Build & Push
      uses: docker/build-push-action@v2
      with:
        push: true
        build-args: |
          version=${{ steps.tag.outputs.tag }}
        tags: ${{ secrets.ACR_ENDPOINT }}/${{ env.HEALTH_CHECK }}:${{ steps.tag.outputs.tag }}        
