name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  HEALTH_CHECK: goat/k8s-goat-health-check
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

 #   - name: Build the Docker image
 #     run: docker build infrastructure/health-check/ --file infrastructure/health-check/Dockerfile --tag ${{ secrets.ACR_ENDPOINT }}/${{ env.HEALTH_CHECK }}:${{ env.GITHUB_RUN_ID }}
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        # list of Docker images to use as base name for tags
        images: |
          ${{ secrets.ACR_ENDPOINT }}/${{ env.HEALTH_CHECK }}
        
        # generate Docker tags based on the following events/attributes
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    - name: Log into registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ACR_ENDPOINT }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}  
    - name: Build & Push
      uses: docker/build-push-action@v2
      with:
        push: true
        build-args: |
          version=${{ env.GITHUB_RUN_ID }}
        tags: ${{ secrets.ACR_ENDPOINT }}/${{ env.HEALTH_CHECK }}:${{ env.GITHUB_RUN_ID }}        
